/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

/**
 *
 * @author PLJC-PC
 */
import java.sql.Connection;
import javax.swing.JOptionPane;
import com.sun.glass.events.KeyEvent;
import java.awt.Component;
import java.awt.Window;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
public class form2 extends javax.swing.JFrame {

    /**
     * Creates new form form2
     */
    String db ="kasir";
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel model1 = new DefaultTableModel();
    //int posisi = 0; 
    public form2() {
        initComponents();
        load_table();
       load_table1();
       clear_text();
    }
    private void load_table1(){
       // DefaultTableModel model1 = new DefaultTableModel();
        model1.addColumn("Nama Barang");
        model1.addColumn("Harga Satuan");
        model1.addColumn("QTY");
        model1.addColumn("Harga Barang");
        tabelbarang.setModel(model1);
}
    

    private void load_table() {
        /*Object[] columns = {
            "No. Kirim","Nama Pembeli","Tanggal Kirim",
            "Kode Batik","Motif Batik","Jumlah Kodi","Total Harga",
            "Biaya Kirim","Presentase","Biaya Administrasi","Total Biaya"
        };*/
       
        model.addColumn("ID Customer");
        model.addColumn("Nama Customer");
        model.addColumn("Kontak");
        model.addColumn("Tanggal beli");
        model.addColumn("Total Harga");
        model.addColumn("Jumlah Yang Dibayarkan");
        model.addColumn("Uang Kembali");
         
        
        
    try {
           
            String sql = "select * from data_pembeli"; // mengambil data yang akan digunakan ,jika kammu punya data yang kamu punya banyak maka tmbhkan kata limit stelah kata mhs, maka yg tebaca dri 0-100 atau lbih
            java.sql.Connection conn = konek.connect(db);
            java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
            while (rs.next()) { // unruk menelusuri data dri awal sampai akhir 
                String[] dataField = {
                   
                    rs.getString("id_customer"),
                    rs.getString("nama"),
                    rs.getString("kontak"),
                    rs.getString("tanggal"),
                    rs.getString("total"),
                    rs.getString("bayar"),
                    rs.getString("kembalian")
                         
                
                    
                };         
                model.addRow(dataField);
                  
                  
            }  
            //model.setColumnIdentifiers(columns);
                
                
               tabel_output.setModel(model);
               tabel_output.setRowSelectionInterval(0, 0);
        }catch (Exception e) {System.out.println("gagal"+e);}
    }
    
     private void clear_text() {
      model1.setRowCount(0);
        
         
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_output = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel_output.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_output.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_outputMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabel_outputMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_output);

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelbarang);

        hapus.setText("Hapus Data");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        jMenu2.setText("Penjualan");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(883, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabel_outputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_outputMouseClicked
        // TODO add your handling code here:
        clear_text();
      //  DefaultTableModel model2 = new DefaultTableModel();
       int posisi=(tabel_output.rowAtPoint(evt.getPoint()));
        try {
           String sql = "";
            sql = "select data_penjualan.nama_barang, harga, qty, jumlah from data_penjualan inner join data_pembeli on data_pembeli.id_customer = data_penjualan.id_customer WHERE data_pembeli.id_customer ='"+model.getValueAt(posisi, 0).toString()+"'";
            //sql = "select data_penjualan.nama_barang, harga, qty, jumlah * from data_penjualan inner join data_pembeli on data_penjualan.id_customer = data_pembeli.id_customer where id_customer = '"+model.getValueAt(posisi, 0).toString()+"'"; 
            java.sql.Connection conn = konek.connect(db);
            java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
            while (rs.next()) { // unruk menelusuri data dri awal sampai akhir 
                String[] dataField = {
                   
                    rs.getString("nama_barang"),
                    rs.getString("harga"),
                    rs.getString("qty"),
                    rs.getString("jumlah")
 
                };         
                model1.addRow(dataField);
                
            }  
            //model.setColumnIdentifiers(columns);
               
                tabelbarang.setModel(model1); 
               tabelbarang.setRowSelectionInterval(0, 0);
        }catch (Exception e) {System.out.println("gagal"+e);}
        
      //  load_table1();
    }//GEN-LAST:event_tabel_outputMouseClicked

    private void tabel_outputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_outputMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_outputMouseEntered

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        form1 fm=new form1();
        fm.setVisible(true);
        fm.setTitle("Kasir Sederhana");
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        
        
        int selectedOption = JOptionPane.showConfirmDialog(null,
        "Apakah anda yakin akan menghapus data ini?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
        try {
            String sql ="delete from data_penjualan and data_pembeli where id_customer='" + model.getValueAt(posisi, WIDTH) + "'";

            java.sql.Connection conn=konek.connect(db);
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        }
        catch (Exception e) {JOptionPane.showMessageDialog(this, e.getMessage());}
        
        load_table();
        clear_text();
        }
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_output;
    private javax.swing.JTable tabelbarang;
    // End of variables declaration//GEN-END:variables
}
